export const ADDRESS_ACTION_TYPE = {
  ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
  ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
  ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE',

  //-------------------------Get aDDRESS details --------------------------//

  GET_ADDRESS_REQUEST: 'GET_ADDRESS_REQUEST',
  GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
  GET_ADDRESS_FAILURE: 'GET_ADDRESS_FAILURE',

  //------------------------ UPDATE  aDDRESS details --------------------------//

  UPDATE_ADDRESS_REQUEST: 'UPDATE_ADDRESS_REQUEST',
  UPDATE_ADDRESS_SUCCESS: 'UPDATE_ADDRESS_SUCCESS',
  UPDATE_ADDRESS_FAILURE: 'UPDATE_ADDRESS_FAILURE',

  //------------------------ DELETE   aDDRESS details --------------------------//

  DELETE_ADDRESS_REQUEST: 'DELETE_ADDRESS_REQUEST',
  DELETE_ADDRESS_SUCCESS: 'DELETE_ADDRESS_SUCCESS',
  DELETE_ADDRESS_FAILURE: 'DELETE_ADDRESS_FAILURE',

  //-----------------------Add Seller Address -----------------------------//

  ADD_SELLER_PICKUP_ADDRESS_REQUEST: 'ADD_SELLER_PICKUP_ADDRESS_REQUEST',
  ADD_SELLER_PICKUP_ADDRESS_SUCCESS: 'ADD_SELLER_PICKUP_ADDRESS_SUCCESS',
  ADD_SELLER_PICKUP_ADDRESS_FAILURE: 'ADD_SELLER_PICKUP_ADDRESS_FAILURE',

  //-------------------------- Get Seller Address ---------------------------//

  GET_SELLER_ADDRESS_REQUEST: 'GET_SELLER_ADDRESS_REQUEST',
  GET_SELLER_ADDRESS_SUCCESS: 'GET_SELLER_ADDRESS_SUCCESS',
  GET_SELLER_ADDRESS_FAILURE: 'GET_SELLER_ADDRESS_FAILURE',
};
