export const AUTH_ACTION_TYPE = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  //-----------------------------cREATE sELLER aCCOUNT --------------
  CREATE_SELLER_ACCOUNT_REQUEST: 'CREATE_SELLER_ACCOUNT_REQUEST',
  CREATE_SELLER_ACCOUNT_SUCCESS: 'CREATE_SELLER_ACCOUNT_SUCCESS',
  CREATE_SELLER_ACCOUNT_FAILURE: 'CREATE_SELLER_ACCOUNT_FAILURE',
};
