export const BANK_ACTION_TYPE = {
  ADD_BANK_DETAILS_REQUEST: 'ADD_BANK_DETAILS_REQUEST',
  ADD_BANK_DETAILS_SUCCESS: 'ADD_BANK_DETAILS_SUCCESS',
  ADD_BANK_DETAILS_FAILURE: 'ADD_BANK_DETAILS_FAILURE',

  //-------------------------Get BAnk details --------------------------//

  GET_BANK_DETAILS_REQUEST: 'GET_BANK_DETAILS_REQUEST',
  GET_BANK_DETAILS_SUCCESS: 'GET_BANK_DETAILS_SUCCESS',
  GET_BANK_DETAILS_FAILURE: 'GET_BANK_DETAILS_FAILURE',

  //------------------------- save seller bank details --------------------------//

  SELLER_ADD_BANK_DETAILS_REQUEST: 'SELLLER_ADD_BANK_DETAILS_REQUEST',
  SELLER_ADD_BANK_DETAILS_SUCCESS: 'SELLER_ADD_BANK_DETAILS_SUCCESS',
  SELLER_ADD_BANK_DETAILS_FAILURE: 'SELLER_ADD_BANK_DETAILS_FAILURE',

  //------------------------- save seller bank details --------------------------//

  SELLER_GET_BANK_DETAILS_REQUEST: 'SELLLER_GET_BANK_DETAILS_REQUEST',
  SELLER_GET_BANK_DETAILS_SUCCESS: 'SELLER_GET_BANK_DETAILS_SUCCESS',
  SELLER_GET_BANK_DETAILS_FAILURE: 'SELLER_GET_BANK_DETAILS_FAILURE',
};
