export const CART_ACTION_TYPE = {
  DISPATCH_CART_DATA_REQUEST: 'DISPATCH_CART_DATA_REQUEST',
  DISPATCH_CART_DATA_SUCCESS: 'DISPATCH_CART_DATA_SUCCESS',
  DISPATCH_CART_DATA_FAILURE: 'DISPATCH_CART_DATA_FAILURE',

  //---------------------------Add to cart ------------------------------------
  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

  //---------------------------Get to cart ------------------------------------

  GET_TO_CART_REQUEST: 'GET_TO_CART_REQUEST',
  GET_TO_CART_SUCCESS: 'GET_TO_CART_SUCCESS',
  GET_TO_CART_FAILURE: 'GET_TO_CART_FAILURE',

  //---------------------------REMOVE FROM  cart ------------------------------------

  REMOVE_FROM_CART_REQUEST: 'REMOVE_FROM_CART_REQUEST',
  REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_FAILURE: 'REMOVE_FROM_CART_FAILURE',
};
