export const CATEGORY_ACTION_TYPE = {
  GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',

  //------------------------------Get Subcategory-----------------------//

  GET_SUB_CATEGORY_REQUEST: 'GET_SUB_CATEGORY_REQUEST',
  GET__SUB_CATEGORY_SUCCESS: 'GET_SUB_CATEGORY_SUCCESS',
  GET_SUB_CATEGORY_FAILURE: 'GET_SUB_CATEGORY_FAILURE',
};
