export const GO_SWIFT_ACTION_TYPE = {
  //-----------------------------Get All token -------------------------------//

  GET_ACCESS_TOKEN_REQUEST: 'GET_ACCESS_TOKEN_REQUEST',
  GET_ACCESS_TOKEN_SUCCESS: 'GET_ACCESS_TOKEN_SUCCESS',
  GET_ACCESS_TOKEN_FAILURE: 'GET_ACCESS_TOKEN_FAILURE',

  //-----------------------------Add address go swift  -------------------------------//

  ADD_PICKUP_ADDRESS_TO_GOSWIFT_REQUEST:
    'ADD_PICKUP_ADDRESS_TO_GOSWIFT_REQUEST',
  ADD_PICKUP_ADDRESS_TO_GOSWIFT_SUCCESS:
    'ADD_PICKUP_ADDRESS_TO_GOSWIFT_SUCCESS',
  ADD_PICKUP_ADDRESS_TO_GOSWIFT_FAILURE:
    'ADD_PICKUP_ADDRESS_TO_GOSWIFT_FAILURE',

  //-----------------------------create new order to go swift  -------------------------------//

  CREATE_NEW_ORDER_GO_SWIFT_REQUEST: 'CREATE_NEW_ORDER_GO_SWIFT_REQUEST',
  CREATE_NEW_ORDER_GO_SWIFT_SUCCESS: 'CREATE_NEW_ORDER_GO_SWIFT_SUCCESS',
  CREATE_NEW_ORDER_GO_SWIFT_FAILURE: 'CREATE_NEW_ORDER_GO_SWIFT_FAILURE',

  //-----------------------------Track  order to go swift  -------------------------------//

  TRACK_ORDER_GO_SWIFT_REQUEST: 'TRACK_ORDER_GO_SWIFT_REQUEST',
  TRACK_ORDER_GO_SWIFT_SUCCESS: 'TRACK_ORDER_GO_SWIFT_SUCCESS',
  TRACK_ORDER_GO_SWIFT_FAILURE: 'TRACK_ORDER_GO_SWIFT_FAILURE',

  //-----------------------------Check pincode go swift  -------------------------------//

  CHECK_PINCODE_GO_SWIFT_REQUEST: 'CHECK_PINCODE_GO_SWIFT_REQUEST',
  CHECK_PINCODE_GO_SWIFT_SUCCESS: 'CHECK_PINCODE_GO_SWIFT_SUCCESS',
  CHECK_PINCODE_GO_SWIFT_FAILURE: 'CHECK_PINCODE_GO_SWIFT_FAILURE',

  //-----------------------------order cancel-------------------------------//

  ORDER_CANCEL_GO_SWIFT_REQUEST: 'ORDER_CANCEL_GO_SWIFT_REQUEST',
  ORDER_CANCEL_GO_SWIFT_SUCCESS: 'ORDER_CANCEL_GO_SWIFT_SUCCESS',
  ORDER_CANCEL_GO_SWIFT_FAILURE: 'ORDER_CANCEL_GO_SWIFT_FAILURE',
};
