export const HELP_CENTER_ACTION_TYPE = {
  SAVE_SUPPORT_TICKET_REQUEST: 'SAVE_SUPPORT_TICKET_REQUEST',
  SAVE_SUPPORT_TICKET_SUCCESS: 'SAVE_SUPPORT_TICKET_SUCCESS',
  SAVE_SUPPORT_TICKET_FAILURE: 'SAVE_SUPPORT_TICKET_FAILURE',

  //-----------------------------Get All Ticket -------------------------------//

  GET_SUPPORT_TICKET_REQUEST: 'GET_SUPPORT_TICKET_REQUEST',
  GET_SUPPORT_TICKET_SUCCESS: 'GET_SUPPORT_TICKET_SUCCESS',
  GET_SUPPORT_TICKET_FAILURE: 'GET_SUPPORT_TICKET_FAILURE',
};
