export const ORDER_ACTION_TYPE = {
  ORDER_PLACED_REQUEST: 'ORDER_PLACED_REQUEST',
  ORDER_PLACED_SUCCESS: 'ORDER_PLACED_SUCCESS',
  ORDER_PLACED_FAILURE: 'ORDER_PLACED_FAILURE',

  //--------------------------------Get Order List ------------------------------------//

  GET_ORDER_LIST_REQUEST: 'GET_ORDER_LIST_REQUEST',
  GET_ORDER_LIST_SUCCESS: 'GET_ORDER_LIST_SUCCESS',
  GET_ORDER_LIST_FAILURE: 'GET_ORDER_LIST_FAILURE',

  //--------------------------------Get Order DETAILS------------------------------------//

  GET_ORDER_DETAILS_REQUEST: 'GET_ORDER_DETAILS_REQUEST',
  GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS',
  GET_ORDER_DETAILS_FAILURE: 'GET_ORDER_DETAILS_FAILURE',

  //-------------------------cancel order----------------------//

  CANCEL_ORDER_PLACED_REQUEST: 'CANCEL_ORDER_PLACED_REQUEST',
  CANCEL_ORDER_PLACED_SUCCESS: 'CANCEL_ORDER_PLACED_SUCCESS',
  CANCEL_ORDER_PLACED_FAILURE: 'CANCEL_ORDER_PLACED_FAILURE',
};
