export const PRODUCTS_ACTION_TYPE = {
  GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',

  // Get Product Deatils

  GET_PRODUCTS_DETAILS_REQUEST: 'GET_PRODUCTS_DETAILS_REQUEST',
  GET_PRODUCTS_DETAILS_SUCCESS: 'GET_PRODUCTS_DETAILS_SUCCESS',
  GET_PRODUCTS_DETAILS_FAILURE: 'GET_PRODUCTS_DETAILS_FAILURE',

  // product thumnail image

  GET_PRODUCTS_THUMBNAIL_REQUEST: 'GET_PRODUCTS_THUMBNAIL_REQUEST',
  GET_PRODUCTS_THUMBNAIL_SUCCESS: 'GET_PRODUCTS_THUMBNAIL_SUCCESS',
  GET_PRODUCTS_THUMBNAIL_FAILURE: 'GET_PRODUCTS_THUMBNAIL_FAILURE',

  // product Review

  GET_PRODUCTS_REVIEW_REQUEST: 'GET_PRODUCTS_REVIEW_REQUEST',
  GET_PRODUCTS_REVIEW_SUCCESS: 'GET_PRODUCTS_REVIEW_SUCCESS',
  GET_PRODUCTS_REVIEW_FAILURE: 'GET_PRODUCTS_REVIEW_FAILURE',

  /// get Simler Product

  GET_SIMMILAR_PRODUCTS_REQUEST: 'GET_SIMMILAR_PRODUCTS_REQUEST',
  GET_SIMMILAR_PRODUCTS_SUCCESS: 'GET_SIMMILAR_PRODUCTS_SUCCESS',
  GET_SIMMILAR_PRODUCTS_FAILURE: 'GET_SIMMILAR_PRODUCTS_FAILURE',

  // Get Product By Category

  GET_PRODUCT_BY_CATEGORY_REQUEST: 'GET_PRODUCT_BY_CATEGORY_REQUEST',
  GET_PRODUCT_BY_CATEGORY_SUCCESS: 'GET_PRODUCT_BY_CATEGORY_SUCCESS',
  GET_PRODUCT_BY_CATEGORY_FAILURE: 'GET_PRODUCT_BY_CATEGORY_FAILURE',

  //-----------------------Add Product review ---------------------------------//

  ADD_PRODUCT_REVIEW_REQUEST: 'ADD_PRODUCT_REVIEW_REQUEST',
  ADD_PRODUCT_REVIEW_SUCCESS: 'ADD_PRODUCT_REVIEW_SUCCESS',
  ADD_PRODUCT_REVIEW_FAILURE: 'ADD_PRODUCT_REVIEW_FAILURE',
};
