export const WISH_LIST_ACTION_TYPE = {
  ADD_WISH_LIST_REQUEST: 'ADD_WISHLIST_REQUEST',
  ADD_WISH_LIST_SUCCESS: 'ADD_WISHLIST_SUCCESS',
  ADD_WISH_LIST_FAILURE: 'ADD_WISHLIST_FAILURE',

  // get wishList

  GET_WISH_LIST_REQUEST: 'GET_WISHLIST_REQUEST',
  GET_WISH_LIST_SUCCESS: 'GET_WISHLIST_SUCCESS',
  GET_WISH_LIST_FAILURE: 'GET_WISHLIST_FAILURE',

  // remove wishlist

  REMOVE_WISH_LIST_REQUEST: 'REMOVE_WISHLIST_REQUEST',
  REMOVE_WISH_LIST_SUCCESS: 'REMOVE_WISHLIST_SUCCESS',
  REMOVE_WISH_LIST_FAILURE: 'REMOVE_WISHLIST_FAILURE',

  // check wishlist

  CHECK_WISH_LIST_REQUEST: 'CHECK_WISHLIST_REQUEST',
  CHECK_WISH_LIST_SUCCESS: 'CHECK_WISHLIST_SUCCESS',
  CHECK_WISH_LIST_FAILURE: 'CHECK_WISHLIST_FAILURE',
};
